# Automates Global Order data and Local Order data extraction

1. Extract Global Order Data
2. Extract Local Order Data
3. Store in data folder

In [1]:
%reload_ext autoreload
%autoreload 2
from tes.data_ingestion import DataRead

#### Create object of class DataRead

In [3]:
ext = DataRead()

#### Call ext_global_order function

In [4]:
l = ext.ext_global_order(4, "itr_test.bz2", "loc_test.bz2")

Current iteration is 0
D:\srg_tES\srg-tes-epilepsy-models\data\connectivity_matrix\mb_communities.npz already exists
DataUtils initialized
0.05106045143057527
Current iteration is 1
D:\srg_tES\srg-tes-epilepsy-models\data\connectivity_matrix\mb_communities.npz already exists
DataUtils initialized
0.5251723886916954
Current iteration is 2
D:\srg_tES\srg-tes-epilepsy-models\data\connectivity_matrix\mb_communities.npz already exists
DataUtils initialized
0.06462403353215974
Current iteration is 3
D:\srg_tES\srg-tes-epilepsy-models\data\connectivity_matrix\mb_communities.npz already exists
DataUtils initialized
0.4884807459364324
Stored Global Order data and Local order data in data folder
Number of transitions is 2

#### Print list of iterations which had transitions

In [ ]:
print(l)

[1, 3]

#### Read store simulation dataframe

In [7]:
ext.data_read_bz2("itr_test.bz2")

              0         1         2         3
0      0.056480  0.114353  0.008069  0.060204
1      0.056199  0.114642  0.008122  0.060472
2      0.055882  0.114837  0.008121  0.060698
3      0.055530  0.114939  0.008066  0.060878
4      0.055145  0.114948  0.007960  0.061014
...         ...       ...       ...       ...
39995  0.040241  0.526267  0.058711  0.484423
39996  0.043028  0.525984  0.060054  0.485450
39997  0.045763  0.525706  0.061495  0.486471
39998  0.048442  0.525436  0.063022  0.487483
39999  0.051060  0.525172  0.064624  0.488481

[40000 rows x 4 columns]

#### Reading stored local order data

In [8]:
ext.data_read_bz2("loc_test.bz2")

           0         1         2         3         4         5         6     \
1 0    0.102846  0.105248  0.107626  0.109970  0.112270  0.114516  0.116702
  1    0.082458  0.083418  0.084228  0.084891  0.085407  0.085779  0.086010
  2    0.080705  0.080621  0.080435  0.080155  0.079787  0.079342  0.078827
  3    0.215395  0.211638  0.207771  0.203799  0.199730  0.195571  0.191330
  4    0.121547  0.123646  0.125580  0.127347  0.128946  0.130376  0.131634
...         ...       ...       ...       ...       ...       ...       ...
3 421  0.367200  0.362755  0.358303  0.353863  0.349451  0.345084  0.340779
  422  0.095834  0.093876  0.092299  0.091127  0.090375  0.090052  0.090160
  423  0.121154  0.121894  0.122434  0.122768  0.122895  0.122810  0.122514
  424  0.155379  0.154604  0.153637  0.152482  0.151145  0.149630  0.147940
  425  0.140837  0.142540  0.144117  0.145566  0.146886  0.148075  0.149135

           7         8         9     ...      4990      4991      4992  \
1 0    0.118822  0.120871  0.122845  ...  0.817249  0.816543  0.815843
  1    0.086102  0.086058  0.085879  ...  0.360010  0.357942  0.356013
  2    0.078252  0.077626  0.076960  ...  0.547610  0.547026  0.546453
  3    0.187017  0.182639  0.178206  ...  0.377949  0.372854  0.367596
  4    0.132719  0.133631  0.134370  ...  0.467231  0.466664  0.466213
...         ...       ...       ...  ...       ...       ...       ...
3 421  0.336555  0.332429  0.328420  ...  0.341013  0.339624  0.338076
  422  0.090693  0.091636  0.092969  ...  0.226908  0.226562  0.225959
  423  0.122004  0.121280  0.120344  ...  0.048478  0.051078  0.053623
  424  0.146082  0.144060  0.141880  ...  0.284086  0.282431  0.280687
  425  0.150065  0.150870  0.151549  ...  0.499064  0.497283  0.495400

           4993      4994      4995      4996      4997      4998      4999
1 0    0.815152  0.814473  0.813808  0.813163  0.812540  0.811944  0.811379
  1    0.354229  0.352598  0.351123  0.349808  0.348655  0.347666  0.346840
  2    0.545892  0.545346  0.544817  0.544309  0.543825  0.543366  0.542937
  3    0.362181  0.356615  0.350905  0.345060  0.339088  0.333000  0.326806
  4    0.465879  0.465662  0.465563  0.465580  0.465709  0.465946  0.466287
...         ...       ...       ...       ...       ...       ...       ...
3 421  0.336391  0.334590  0.332693  0.330720  0.328692  0.326626  0.324540
  422  0.225106  0.224009  0.222676  0.221116  0.219338  0.217349  0.215161
  423  0.056102  0.058507  0.060830  0.063067  0.065211  0.067259  0.069206
  424  0.278859  0.276948  0.274958  0.272892  0.270753  0.268543  0.266264
  425  0.493420  0.491347  0.489188  0.486950  0.484641  0.482269  0.479842

[852 rows x 5000 columns]